import type { Offer } from "@/lib/types";

export const mockOffers: Offer[] = [
  {
    id: "off_mock_1",
    merchant_id: "m_001",
    merchant_name: "Blue Bottle Coffee",
    merchant_category: "cafe",
    headline: "Cold outside? Your cappuccino is waiting.",
    subtext: "2 min walk \u00b7 Rockefeller Center",
    description:
      "Warm up at Blue Bottle Coffee. Quiet right now, no queue, your usual spot by the window is free.",
    discount_value: "15%",
    discount_type: "percentage_discount",
    context_tags: ["rainy", "cold", "quiet_cafes"],
    why_now: "Raining and unusually quiet for a Saturday afternoon.",
    created_at: new Date().toISOString(),
    expires_at: new Date(Date.now() + 25 * 60_000).toISOString(),
    style: {
      background_gradient: ["#3b4a5a", "#1f2a36"],
      tone: "warm",
      headline_style: "emotional",
    },
    status: "active",
    distance_meters: 180,
    redemption_token: null,
  },
  {
    id: "off_mock_2",
    merchant_id: "m_002",
    merchant_name: "Joe's Pizza",
    merchant_category: "restaurant",
    headline: "Rain keeping people away. The oven is not.",
    subtext: "4 min walk \u00b7 Greenwich Village",
    description:
      "Iconic New York slices since 1975. Wet streets mean shorter wait. Fresh out of the oven.",
    discount_value: "10%",
    discount_type: "percentage_discount",
    context_tags: ["rainy", "lunch_hour"],
    why_now: "Rain is keeping foot traffic low. Pizza is fresh.",
    created_at: new Date().toISOString(),
    expires_at: new Date(Date.now() + 18 * 60_000).toISOString(),
    style: {
      background_gradient: ["#c2410c", "#7c2d12"],
      tone: "playful",
      headline_style: "emotional",
    },
    status: "active",
    distance_meters: 350,
    redemption_token: null,
  },
  {
    id: "off_mock_3",
    merchant_id: "m_003",
    merchant_name: "The Strand Bookstore",
    merchant_category: "bookstore",
    headline: "18 miles of books. Perfect afternoon for it.",
    subtext: "6 min walk \u00b7 Union Square",
    description: "Weekend rain has cleared the usual crowds. The stacks are yours.",
    discount_value: "20%",
    discount_type: "percentage_discount",
    context_tags: ["rainy", "weekend", "quiet_period"],
    why_now: "Weekend rain cleared the crowds. Best browsing conditions in weeks.",
    created_at: new Date().toISOString(),
    expires_at: new Date(Date.now() + 45 * 60_000).toISOString(),
    style: {
      background_gradient: ["#3f3a52", "#1f1d2b"],
      tone: "sophisticated",
      headline_style: "emotional",
    },
    status: "active",
    distance_meters: 520,
    redemption_token: null,
  },
];
